apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{values.name}}
  labels:
    app: ${{values.name}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${{values.name}}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${{values.name}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${{values.name}}
subjects:
  - kind: ServiceAccount
    name: ${{values.name}}
